# -*- coding: utf-8 -*-
"""Task1.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11GiUdszHJRi30AceeoSxKJ_5Vxo7_FWC
"""

import pandas as pd
import numpy as np
dataset=pd.read_csv("/content/sample_data/train.csv")

print(dataset.head())

print(dataset.info())

print(dataset.describe())

print("Rows and Columns:", dataset.shape)

print(dataset.isnull().sum())

print("Identifying Numerical Column")
print(dataset.select_dtypes(include=np.number).columns)

print("Identifying Categorical Column")
print(dataset.select_dtypes(include="object").columns)

## Data Story

The following dataset contains information about 891 passengers.
It includes both numerical and categorical columns describing passenger details.
Three columns contain missing values, especially Age, Cabin and Embarked.
The Cabin column has the largest number of missing entries.
This dataset appears suitable for exploring how different passenger characteristics influenced survival.


